### PR TITLE
Feature/code cleaning

### PR DESCRIPTION
**Pull request by NicholasJallan**
Massive cleaning of the code

### CODE REVIEW

**Comment by vttn** [comment]
Hello @NicholasJallan,

Thank you for the PR.

Unfortunately we can not accept it at this time. This library is generated via OpenAPi/Swagger. This means we can not accept limited scoped PRs.

However we will review it.

Regards,

@vttn

**Comment by NicholasJallan** [comment]
Understood, but it's quite sad as the java code you're currently running is really, really bad. As example, it's as good as writing a professional website with Ms Word 6.0 and export it as html…

**Comment by thomashunziker** [comment]
@NicholasJallan We are looking into the changes you are proposing. They are valid. However as Victor pointed out we need to port them into the template with which we generate the SDK.

**Comment by NicholasJallan** [comment]
@thomashunziker : feel free to point out where this template is, I might try to improve it directly then.

**Comment by vttn** [comment]
@NicholasJallan you can find the templates here https://github.com/swagger-api/swagger-codegen/tree/v2.4.16/modules/swagger-codegen/src/main/resources/Java

**Pull request closed without merging**
